chore(website): upload to ipfs

diff --git a/.github/workflows/upload-to-ipfs.yml b/.github/workflows/upload-to-ipfs.yml
--- a/.github/workflows/upload-to-ipfs.yml
+++ b/.github/workflows/upload-to-ipfs.yml
@@ -1,14 +1,31 @@
 name: Upload Website to IPFS
 
-on: workflow_dispatch
+on:
+  workflow_dispatch:
+    inputs:
+      release_number:
+        description: 'Release Tag (e.g., v1.2.3)'
+        required: true
+        type: string
 
 jobs:
-  upload-ipfs:
+  validate-and-upload:
     runs-on: ubuntu-latest
-    permissions:
-      pull-requests: write
     steps:
+      - name: Validate release exists
+        run: |
+          RELEASE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.event.inputs.release_number }}")
+          if [[ $(echo $RELEASE | jq -r '.message') == "Not Found" ]]; then
+            echo "Error: Release ${{ github.event.inputs.release_number }} not found"
+            exit 1
+          fi
+          echo "Release exists, proceeding with checkout"
+
       - uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.inputs.release_number }}
+          
       - uses: pnpm/action-setup@v4
       - uses: actions/setup-node@v4
         with:
@@ -16,17 +33,21 @@ jobs:
           node-version: '20.5.1'
 
       - run: pnpm i --frozen-lockfile
-      - run: pnpm build
 
       - run: echo "${{ vars.NEXT_ENV }}" > packages/website/.env.local
-      - run: cd packages/website && pnpm build
+      - run: pnpm build:website
 
-      - uses: dbeal-eth/ipfs-github-action@master
-        id: ipfs
-        with:
-          path_to_add: packages/website/out
-          cluster_host: ${{ secrets.IPFS_CLUSTER_ADDR }}
-          cluster_user: ${{ secrets.IPFS_CLUSTER_USER }}
-          cluster_password: ${{ secrets.IPFS_CLUSTER_PASSWORD }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Create ZIP file
+        run: zip -r "build-${{ github.event.inputs.release_number }}.zip" packages/website/out
+
+      - name: Upload to Cannon Repo
+        run: |
+          curl -X POST \
+            "https://repo.usecannon.com/api/v0/add?wrap-with-directory=true" \
+            -H "Authorization: Bearer ${{ secrets.REPO_CANNON_JWT }}" \
+            -H "Content-Type: multipart/form-data" \
+            -F "file=@build-${{ github.event.inputs.release_number }}.zip"
+
+  
+
+      
